### ISSUE TITLE
Can't find the GTA World chat log.

### ISSUE THREAD

**Issue by esFerDev** [AdvGTAW/GTAW-Log-Parser#2]
I was trying to execute Parser Mini and Log Parser but it gives me the same error:
```
---------------------------
Error
---------------------------
Can't find the GTA World chat log.
---------------------------
Aceptar   
---------------------------
```

Notes: I'm playing in ES GTA WORLD at the moment.

**Comment by AdvGTAW** [comment]
The code is designed to search for a server version  on load: 

```c#
**if (!Regex.IsMatch(log, "\\\"server_version\\\":\\\"GTA World[^\"]*\""))**
``` 

I know the ES Gta world may have a different one, so it may be worth forking this and making a version which supports that, like others have done.
